### ISSUE TITLE
./makeall fail

### ISSUE THREAD

**Issue by jordur** [fg6/smis#1]
Hi @fg6 !
First of all thank you for the usage of bwa on the smis scaffolding tool, great idea!
However, I am trying to unsuccessfully configure the tool, since it seems that spinner_pg file was not where expected:

```
gapest_pg.o: In function `StdDev':
gapest.c:(.text+0x19a): undefined reference to `sqrt'
gapest_pg.o: In function `SetNormalDistribution':
gapest.c:(.text+0x34c): undefined reference to `exp'
gapest_pg.o: In function `LogLikelihood':
gapest.c:(.text+0x8d9): undefined reference to `log'
gapest_pg.o: In function `MultiDistributionLogLikelihood':
gapest.c:(.text+0xad9): undefined reference to `log'
collect2: error: ld returned 1 exit status
makefile:4: recipe for target 'spinner_pg' failed
make: *** [spinner_pg] Error 1
mv: ha fallat stat() sobre 'spinner_pg': File not found

```
Moreover:
$ whereis bamtools
bamtools: /media/bec2-jcalvete/Disc_Dur/Feina_Jordi/programes/bin/bamtools
$ export MYBAMTOOLS=/media/bec2-jcalvete/Disc_Dur/Feina_Jordi/programes/bin/bamtools

Could you help me with this issue?
Thank you in advance

**Comment by fg6** [comment]
Hi jordur!
hmm it seems the compiler is not able to locate the math library, 
which OS are you using to compile it? Linux or?
Can you also tell me which gcc version?

Cheers,
Fran

**Comment by jordur** [comment]
Sure! Here the information:
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 

```
However, as you said in the README file, zlib should be on the path. I am not used to zlib packaga so I am not sure if I agree that term... 

Thank you.

**Comment by fg6** [comment]
I am not able to reproduce your problem so it's a bit difficult to guess what is going on. 
I think is an environment issue. Can you tell me the results of the following:
Step 1.  cd  your_smis_folder/src/spinner
Step 2.  gcc -c spinner.c -o spinner_pg.o
Step 3.  gcc -c readlist.c -o readlist_pg.o
Step 4.  gcc -c scaffoldlist.c -o scaffoldlist_pg.o
Step 5.  gcc -c refine.c -o refine_pg.o
Step 6.  gcc -c gapest.c -o gapest_pg.o
Step 7.  gcc -lm spinner_pg.o readlist_pg.o scaffoldlist_pg.o refine_pg.o gapest_pg.o -o spinner_pg

Thanks,
Fran

**Comment by jordur** [comment]
Sure! Attached you will find the file with all the outputs.
Thank you very much for your help!

[logs.md.zip](https://github.com/fg6/smis/files/1152866/logs.md.zip)

**Comment by fg6** [comment]
ok, in the same folder do you see the following files?:
gapest_pg.o  readlist_pg.o  refine_pg.o  scaffoldlist_pg.o

if you see them, then try this command:
$ gcc spinner_pg.o readlist_pg.o scaffoldlist_pg.o refine_pg.o gapest_pg.o -o spinner_pg  -lm

**Comment by jordur** [comment]
Done! Then, should I go forward to the run/setup step?

**Comment by fg6** [comment]
no errors this time?
If no errors, please delete the smis folder and clone it again, I have changed the makefile in the new version, so you can just follow the instructions again and check if everything is fine!

**Comment by jordur** [comment]
Hi @fg6, 
in fact nothing at all was done. I mean, attached you will find the log file (what I did after cloned again) and the executable .sh files. What is weird for me is even commenting most of mysmissv.sh script (as you can see in the mysmissv_mod.sh script) a echo statement of the sfile variable (line 11) was not displayed. 
Maybe I am doing something wrong?
Thank you for your help
[smis.zip](https://github.com/fg6/smis/files/1153577/smis.zip)

**Comment by fg6** [comment]
hmm yes that's weird.
Let's do a few steps:  [test.zip](https://github.com/fg6/smis/files/1155252/test.zip)

1. Can you check which bash are you using in your terminal? ( $ which bash )
2. launch test1.sh:
      $  chmod +x test1.sh; ./test1.sh
   what's the output?
and same for test2.sh, test3.sh and test4.sh

let me know!

**Comment by jordur** [comment]
Here the outputs:

```
bec2-jcalvete@Bec2-jcalvete:~/Baixades$ ./test1.sh 
looking for /media/bec2-jcalvete/Elements/Minion_Bjararaca/Bjararaca_4/processing/Bjar1-2-4/good/scaffolding/scaffolding_1/mysettings.sh:
Ok, I found it
bec2-jcalvete@Bec2-jcalvete:~/Baixades$ ./test2.sh 
looking for /media/bec2-jcalvete/Elements/Minion_Bjararaca/Bjararaca_4/processing/Bjar1-2-4/good/scaffolding/scaffolding_1/mysettings.sh:
 Ok, I found it
 I will try to source your file now:
 sourcing successful!
3000
bec2-jcalvete@Bec2-jcalvete:~/Baixades$ ./test3.sh 
looking for /media/bec2-jcalvete/Elements/Minion_Bjararaca/Bjararaca_4/processing/Bjar1-2-4/good/scaffolding/scaffolding_1/mysettings.sh:
 Ok, I found it
 I will try to source your file now:
bec2-jcalvete@Bec2-jcalvete:~/Baixades$ ./test4.sh 
looking for /media/bec2-jcalvete/Elements/Minion_Bjararaca/Bjararaca_4/processing/Bjar1-2-4/good/scaffolding/scaffolding_1/mysettings.sh:
 Ok, I found it
 I will try to source your file now:

```

And I am using /bin/bash

Thank you for your time!

**Comment by jordur** [comment]
It seems that my system is not comfortable with "set -o errexit"... what actually does it mean? I am looking for information about it. It seems to be used to define a set of variables, isn't it?

**Comment by fg6** [comment]
hmm. it seems your bash doesn't like the "set -o errexit" settings (line 2 of the scripts)
Quick solution: just drop this line from the smissv.sh script and see if it works now.

Better solution: the  "set -o errexit" is supposed to kill the script if an error occurs. I don't know which sort of error occur in your case that make the script crash. This would need investigating, it seems the script is not able to source the mysettings.sh script. Anyway if the pipeline run successfully after dropping this line the problem is probably some weird bash setting, I would need to have a closer look.
Let me know if it works without the "set -o errexit" line.

Another possible issue: the reads are supposed to be in a fastq file, I am not sure it will work with a fasta.
let me know if it doesn't, I'll look for a quick solution!
Cheers,
Fran
