### ISSUE TITLE
smis_shred / smis_rename /  smis_sort  no such file found in smissv-bin

### ISSUE THREAD

**Issue by bhagya-ct** [fg6/smis#3]
Dear Developer,

I am encountering following error.
Infact I do see only one file in the smissv-bin folder.

./mysmissv.sh: line 78: /home/mml/Bhagya/softwares/smis/smissv-bin/smis_shred: No such file or directory
./mysmissv.sh: line 87: /home/mml/Bhagya/softwares/smis/smissv-bin/smis_rename: No such file or directory
[bwa_index] fail to open file 'genome.fasta' : No such file or directory
[E::bwa_idx_load_from_disk] fail to locate the index files
./mysmissv.sh: line 128: /home/mml/Bhagya/softwares/smis/smissv-bin/smis_sort: No such file or directory
wc: '/media/mml/7f555590-c3e2-4192-a443-b767d932b613/RNAseq/RNAseq/KG/ct-pacbio_data/CATR/tempWork/genome-matepair-*': No such file or directory
cannot open file genome.fasta
mv: cannot stat 'spinner-sp2b.fasta': No such file or directory

 Scaffolds are in spinner_scaffolds.fasta
 Summary of parameters used are in  /media/mml/7f555590-c3e2-4192-a443-b767d932b613/RNAseq/RNAseq/KG/ct-pacbio_data/CATR/logs/launchedas_1506064524.txt
 Log is in  /media/mml/7f555590-c3e2-4192-a443-b767d932b613/RNAseq/RNAseq/KG/ct-pacbio_data/CATR/logs/output_1506064524.txt

It will be a great help if you can suggest me where I am wrong.

Thanks
Bhagya C T

**Comment by fg6** [comment]
Dear Bhagya,
thanks for the info. It seems something during the installation step didn't work. 
Did you have any errors when you ran the makeall.sh?

Please let me know which gcc version are you using and 
please check if your MYBAMTOOLS variable is set ok.
Can you also report what's in your /home/mml/Bhagya/softwares/smis/smissv-bin/ folder?

Thank you,
Francesca

**Comment by bhagya-ct** [comment]
mml@mml-desktop:~/Bhagya/softwares$ export MYBAMTOOLS=/home/mml/Bhagya/softwares/bamtools-build
mml@mml-desktop:~/Bhagya/softwares$ git clone https://github.com/fg6/smis.git
Cloning into 'smis'...
remote: Counting objects: 159, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 159 (delta 6), reused 12 (delta 5), pack-reused 142
Receiving objects: 100% (159/159), 103.84 KiB | 137.00 KiB/s, done.
Resolving deltas: 100% (65/65), done.
Checking connectivity... done.
mml@mml-desktop:~/Bhagya/softwares$ cd smis/
mml@mml-desktop:~/Bhagya/softwares/smis$ ./makeall.sh 
Cloning into 'bamtools'...
remote: Counting objects: 4145, done.
remote: Total 4145 (delta 0), reused 0 (delta 0), pack-reused 4145
Receiving objects: 100% (4145/4145), 2.51 MiB | 857.00 KiB/s, done.
Resolving deltas: 100% (2769/2769), done.
Checking connectivity... done.
Note: checking out '71392a251aaea8b797661846b2878e16efd04285'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 71392a2... Minor version bump - 2.4.0  - Added support for custom header tags.  - Suppressed clang compiler warnings.
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mml/Bhagya/softwares/smis/src/bamtools/build
Scanning dependencies of target SharedHeaders
[  0%] Built target SharedHeaders
Scanning dependencies of target BamTools
[  0%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamAlignment.cpp.o
[  1%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamMultiReader.cpp.o
[  2%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamReader.cpp.o
[  3%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamWriter.cpp.o
[  4%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamHeader.cpp.o
[  5%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamProgram.cpp.o
[  6%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamProgramChain.cpp.o
[  7%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamReadGroup.cpp.o
[  8%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamReadGroupDictionary.cpp.o
[  9%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamSequence.cpp.o
[ 10%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamSequenceDictionary.cpp.o
[ 11%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamHeader_p.cpp.o
[ 12%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamMultiReader_p.cpp.o
[ 13%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamRandomAccessController_p.cpp.o
[ 14%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamReader_p.cpp.o
[ 15%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamWriter_p.cpp.o
[ 16%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamIndexFactory_p.cpp.o
[ 17%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamStandardIndex_p.cpp.o
/home/mml/Bhagya/softwares/smis/src/bamtools/src/api/internal/index/BamStandardIndex_p.cpp: In member function ‘void BamTools::Internal::BamStandardIndex::WriteLinearOffsets(const int&, BamTools::Internal::BaiLinearOffsetVector&)’:
/home/mml/Bhagya/softwares/smis/src/bamtools/src/api/internal/index/BamStandardIndex_p.cpp:958:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ( numBytesWritten != (sizeof(offsetCount) + linearOffsets.size()*sizeof(uint64_t)) )
                          ^
[ 18%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamToolsIndex_p.cpp.o
[ 19%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamDeviceFactory_p.cpp.o
[ 20%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamFile_p.cpp.o
[ 21%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamFtp_p.cpp.o
[ 22%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamHttp_p.cpp.o
/home/mml/Bhagya/softwares/smis/src/bamtools/src/api/internal/io/BamHttp_p.cpp: In member function ‘bool BamTools::Internal::BamHttp::SendGetRequest(size_t)’:
/home/mml/Bhagya/softwares/smis/src/bamtools/src/api/internal/io/BamHttp_p.cpp:409:59: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ( WriteToSocket(requestHeader.c_str(), headerSize) != headerSize ) {
                                                           ^
/home/mml/Bhagya/softwares/smis/src/bamtools/src/api/internal/io/BamHttp_p.cpp: In member function ‘bool BamTools::Internal::BamHttp::SendHeadRequest()’:
/home/mml/Bhagya/softwares/smis/src/bamtools/src/api/internal/io/BamHttp_p.cpp:501:59: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ( WriteToSocket(requestHeader.c_str(), headerSize) != headerSize ) {
                                                           ^
[ 23%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamPipe_p.cpp.o
[ 24%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BgzfStream_p.cpp.o
[ 25%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/ByteArray_p.cpp.o
[ 26%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/HostAddress_p.cpp.o
[ 27%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/HostInfo_p.cpp.o
[ 28%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/HttpHeader_p.cpp.o
[ 29%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/ILocalIODevice_p.cpp.o
[ 30%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/RollingBuffer_p.cpp.o
[ 31%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/TcpSocket_p.cpp.o
[ 32%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/TcpSocketEngine_p.cpp.o
[ 33%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/TcpSocketEngine_unix_p.cpp.o
[ 34%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/sam/SamFormatParser_p.cpp.o
[ 35%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/sam/SamFormatPrinter_p.cpp.o
[ 36%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/sam/SamHeaderValidator_p.cpp.o
[ 37%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/utils/BamException_p.cpp.o
[ 38%] Linking CXX shared library ../../../lib/libbamtools.so
[ 38%] Built target BamTools
Scanning dependencies of target AlgorithmsHeaders
[ 38%] Built target AlgorithmsHeaders
Scanning dependencies of target BamTools-static
[ 39%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/BamAlignment.cpp.o
[ 40%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/BamMultiReader.cpp.o
[ 41%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/BamReader.cpp.o
[ 42%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/BamWriter.cpp.o
[ 43%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/SamHeader.cpp.o
[ 44%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/SamProgram.cpp.o
[ 45%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/SamProgramChain.cpp.o
[ 46%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/SamReadGroup.cpp.o
[ 47%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/SamReadGroupDictionary.cpp.o
[ 48%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/SamSequence.cpp.o
[ 49%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/SamSequenceDictionary.cpp.o
[ 50%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/bam/BamHeader_p.cpp.o
[ 50%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/bam/BamMultiReader_p.cpp.o
[ 51%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/bam/BamRandomAccessController_p.cpp.o
[ 52%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/bam/BamReader_p.cpp.o
[ 53%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/bam/BamWriter_p.cpp.o
[ 54%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/index/BamIndexFactory_p.cpp.o
[ 55%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/index/BamStandardIndex_p.cpp.o
/home/mml/Bhagya/softwares/smis/src/bamtools/src/api/internal/index/BamStandardIndex_p.cpp: In member function ‘void BamTools::Internal::BamStandardIndex::WriteLinearOffsets(const int&, BamTools::Internal::BaiLinearOffsetVector&)’:
/home/mml/Bhagya/softwares/smis/src/bamtools/src/api/internal/index/BamStandardIndex_p.cpp:958:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ( numBytesWritten != (sizeof(offsetCount) + linearOffsets.size()*sizeof(uint64_t)) )
                          ^
[ 56%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/index/BamToolsIndex_p.cpp.o
[ 57%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/BamDeviceFactory_p.cpp.o
[ 58%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/BamFile_p.cpp.o
[ 59%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/BamFtp_p.cpp.o
[ 60%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/BamHttp_p.cpp.o
/home/mml/Bhagya/softwares/smis/src/bamtools/src/api/internal/io/BamHttp_p.cpp: In member function ‘bool BamTools::Internal::BamHttp::SendGetRequest(size_t)’:
/home/mml/Bhagya/softwares/smis/src/bamtools/src/api/internal/io/BamHttp_p.cpp:409:59: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ( WriteToSocket(requestHeader.c_str(), headerSize) != headerSize ) {
                                                           ^
/home/mml/Bhagya/softwares/smis/src/bamtools/src/api/internal/io/BamHttp_p.cpp: In member function ‘bool BamTools::Internal::BamHttp::SendHeadRequest()’:
/home/mml/Bhagya/softwares/smis/src/bamtools/src/api/internal/io/BamHttp_p.cpp:501:59: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ( WriteToSocket(requestHeader.c_str(), headerSize) != headerSize ) {
                                                           ^
[ 61%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/BamPipe_p.cpp.o
[ 62%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/BgzfStream_p.cpp.o
[ 63%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/ByteArray_p.cpp.o
[ 64%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/HostAddress_p.cpp.o
[ 65%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/HostInfo_p.cpp.o
[ 66%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/HttpHeader_p.cpp.o
[ 67%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/ILocalIODevice_p.cpp.o
[ 68%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/RollingBuffer_p.cpp.o
[ 69%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/TcpSocket_p.cpp.o
[ 70%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/TcpSocketEngine_p.cpp.o
[ 71%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/TcpSocketEngine_unix_p.cpp.o
[ 72%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/sam/SamFormatParser_p.cpp.o
[ 73%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/sam/SamFormatPrinter_p.cpp.o
[ 74%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/sam/SamHeaderValidator_p.cpp.o
[ 75%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/utils/BamException_p.cpp.o
[ 76%] Linking CXX static library ../../../lib/libbamtools.a
[ 76%] Built target BamTools-static
Scanning dependencies of target APIHeaders
[ 76%] Built target APIHeaders
Scanning dependencies of target jsoncpp
[ 77%] Building CXX object src/third_party/jsoncpp/CMakeFiles/jsoncpp.dir/json_reader.cpp.o
[ 78%] Building CXX object src/third_party/jsoncpp/CMakeFiles/jsoncpp.dir/json_value.cpp.o
[ 79%] Building CXX object src/third_party/jsoncpp/CMakeFiles/jsoncpp.dir/json_writer.cpp.o
[ 80%] Linking CXX static library ../../../../lib/libjsoncpp.a
[ 80%] Built target jsoncpp
Scanning dependencies of target BamTools-utils
[ 81%] Building CXX object src/utils/CMakeFiles/BamTools-utils.dir/bamtools_fasta.cpp.o
[ 82%] Building CXX object src/utils/CMakeFiles/BamTools-utils.dir/bamtools_options.cpp.o
[ 83%] Building CXX object src/utils/CMakeFiles/BamTools-utils.dir/bamtools_pileup_engine.cpp.o
[ 84%] Building CXX object src/utils/CMakeFiles/BamTools-utils.dir/bamtools_utilities.cpp.o
[ 85%] Linking CXX static library ../../../lib/libbamtools-utils.a
[ 85%] Built target BamTools-utils
Scanning dependencies of target bamtools_cmd
[ 86%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_convert.cpp.o
[ 87%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_count.cpp.o
[ 88%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_coverage.cpp.o
[ 89%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_filter.cpp.o
[ 90%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_header.cpp.o
[ 91%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_index.cpp.o
[ 92%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_merge.cpp.o
[ 93%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_random.cpp.o
[ 94%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_resolve.cpp.o
[ 95%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_revert.cpp.o
[ 96%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_sort.cpp.o
[ 97%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_split.cpp.o
[ 98%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_stats.cpp.o
[ 99%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools.cpp.o
[100%] Linking CXX executable ../../../bin/bamtools
[100%] Built target bamtools_cmd
c++ -O2  -I/lustre/scratch117/sciops/team117/hpag/fg6/analysis/Tests/smis/src/bamtools/include -Wl,-rpath,/lustre/scratch117/sciops/team117/hpag/fg6/analysis/Tests/smis/src/bamtools/lib   -c -o smis_sort.o smis_sort.c
smis_sort.c:27:27: fatal error: api/BamReader.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'smis_sort.o' failed
make: *** [smis_sort.o] Error 1
cp: cannot stat 'smis_sort': No such file or directory
cp: cannot stat 'smis_rename': No such file or directory
cp: cannot stat 'smis_shred': No such file or directory
cp: cannot stat 'smis_select_chr': No such file or directory
rm: cannot remove '*.o': No such file or directory
gcc -c spinner.c -o spinner_pg.o -pg
spinner.c: In function ‘LoadFiles’:
spinner.c:127:11: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘int_least64_t {aka long int}’ [-Wformat=]
    printf("Total number of reads is now %d \n",readList->readNum);
           ^
spinner.c:187:43: warning: too many arguments for format [-Wformat-extra-args]
  if ( contigList->numInName == 7 ) printf("Assuming standardised names for contigs <six characters><contignumber><other> \n", contig
                                           ^
gcc -c readlist.c -o readlist_pg.o -pg
readlist.c: In function ‘LoadSmalt’:
readlist.c:101:11: warning: implicit declaration of function ‘GetIndexFromName’ [-Wimplicit-function-declaration]
     index=GetIndexFromName(contigName, contigList);
           ^
readlist.c:106:17: warning: format ‘%d’ expects argument of type ‘int *’, but argument 8 has type ‘char *’ [-Wformat=]
     sscanf(line,"%s %*s %*s %*s %s %s %" SCN32 " %" SCN32 " %*s %d",
                 ^
readlist.c:143:21: warning: format not a string literal and no format arguments [-Wformat-security]
      fprintf(stderr,line);
                     ^
gcc -c scaffoldlist.c -o scaffoldlist_pg.o -pg
scaffoldlist.c: In function ‘RemoveDuplicatePairs’:
scaffoldlist.c:102:9: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘int_least32_t {aka int}’ [-Wformat=]
  printf("(DUPLICATES) %ld duplicate read pairs found \n", totalDuplicates);
         ^
scaffoldlist.c: In function ‘LoadFastq’:
scaffoldlist.c:763:33: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘int_least32_t {aka int}’ [-Wformat=]
                  fprintf(stderr,"Warning: different length for base and qual: %ld %ld\n", contigLen,  contigLen2);
                                 ^
scaffoldlist.c:763:33: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘int_least32_t {aka int}’ [-Wformat=]
scaffoldlist.c:768:9: warning: too many arguments for format [-Wformat-extra-args]
  printf("----- LoadFastq: Read fastq file.\n",k);
         ^
scaffoldlist.c: In function ‘SaveContigsInScaffoldsProperFormat’:
scaffoldlist.c:957:16: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘int_fast16_t {aka long int}’ [-Wformat=]
    fprintf(fp, "gap %" PRI32 " %d %" PRI64 " %d\n",
                ^
scaffoldlist.c: In function ‘SaveGDF’:
scaffoldlist.c:1043:16: warning: format ‘%d’ expects argument of type ‘int’, but argument 7 has type ‘int_fast16_t {aka long int}’ [-Wformat=]
    fprintf(fp, "%s,%s,%s,%f,%d\n", scaf->frontContig->contig->name,
                ^
scaffoldlist.c:1051:16: warning: format ‘%d’ expects argument of type ‘int’, but argument 7 has type ‘int_fast16_t {aka long int}’ [-Wformat=]
    fprintf(fp, "%s,%s,%s,%f,%d\n", scaf->frontContig->contig->name,
                ^
scaffoldlist.c: In function ‘MakeEdgesFromReads’:
scaffoldlist.c:1273:9: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘int_least64_t {aka long int}’ [-Wformat=]
  printf("# Half edges: %d \n", numHe);
         ^
scaffoldlist.c:1329:9: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘int_least64_t {aka long int}’ [-Wformat=]
  printf("Number of edges: %d \n",scaffoldList->edgeNum);
         ^
gcc -c refine.c -o refine_pg.o -pg
refine.c: In function ‘ValidateReadPositions’:
refine.c:35:12: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘int’ [-Wformat=]
     printf("(WARNING) OffsetReadPositionInHalfEdgeList: out of bounds, dir1 %d new len %ld gap %ld start %ld end %ld len1 %ld len2 %
            ^
refine.c:35:12: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘int’ [-Wformat=]
refine.c:35:12: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 5 has type ‘int_least32_t {aka int}’ [-Wformat=]
refine.c:35:12: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 6 has type ‘int_least32_t {aka int}’ [-Wformat=]
refine.c:35:12: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘int_least32_t {aka int}’ [-Wformat=]
refine.c:35:12: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 8 has type ‘int_least32_t {aka int}’ [-Wformat=]
refine.c: In function ‘ResolveMultipleEdges’:
refine.c:285:22: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘int_least32_t {aka int}’ [-Wformat=]
  if (verbose) printf("(NUM-MULTI) there are %ld unresolved multiple edges \n", numMulti);
                      ^
refine.c: In function ‘FindClosest’:
refine.c:810:57: warning: implicit declaration of function ‘GetHalfEdgeRange’ [-Wimplicit-function-declaration]
   closest->edge->numGoodPair, closest->edge->numBiotin, GetHalfEdgeRange(closest), closest->edge->meanScore);
                                                         ^
refine.c:807:22: warning: format ‘%d’ expects argument of type ‘int’, but argument 7 has type ‘int_fast16_t {aka long int}’ [-Wformat=]
  if (verbose) printf("closest is %s (%s) dir %" PRIBOOLF " len %" PRI32 " gap %f num %d bio %d range %d score %f\n", 
                      ^
refine.c:807:22: warning: format ‘%d’ expects argument of type ‘int’, but argument 8 has type ‘int_fast16_t {aka long int}’ [-Wformat=]
refine.c:830:24: warning: format ‘%d’ expects argument of type ‘int’, but argument 7 has type ‘int_fast16_t {aka long int}’ [-Wformat=]
    if (verbose) printf("conflict with %s (%s) dir %" PRIBOOLF " len %" PRI32 " gap %f num %d bio %d range %d score %f\n",
                        ^
refine.c:830:24: warning: format ‘%d’ expects argument of type ‘int’, but argument 8 has type ‘int_fast16_t {aka long int}’ [-Wformat=]
gcc -c gapest.c -o gapest_pg.o -pg
gapest.c: In function ‘LoadInsertSizeSamples’:
gapest.c:329:9: warning: implicit declaration of function ‘GetIndexFromName’ [-Wimplicit-function-declaration]
   index=GetIndexFromName(contigName, contigList);
         ^
gcc spinner_pg.o readlist_pg.o scaffoldlist_pg.o refine_pg.o gapest_pg.o -o spinner_pg -pg -lm
  !! Error:  smis_sort  not installed properly!


bamtool  was working fine, i did not bother much about it, now I realised that was a mistake.  
gcc version : 5.4.0
I do see even after specifying MYBAMTOOLS, I am encountering fatal error: api/BamReader.h: No such file or directory.
Thank you for correcting me.
Guide me how to fix this fatal error.

**Comment by fg6** [comment]
Thanks. 
Sorry I updated something in the repo this morning but there was a mistake. Can you try again cloning and compiling?
Thank you

**Comment by bhagya-ct** [comment]
Hello, 

Thank you, Installation was successful.
Getting Segmentation fault.
./mysmissv.sh
./mysmissv.sh: line 81:  7758 Segmentation fault      (core dumped) $bindir/smis_shred -rlength $fakelen -step $step -minlen $minlen $fqfile fakemates_1.fastq fakemates_2.fastq >> $outp
Cannot open file
./mysmissv.sh: line 90:  7760 Segmentation fault      (core dumped) $bindir/smis_rename $fafile genome.fasta
Starting at 1506156060
Done reading at 1506156060 Total time so far 0
./mysmissv.sh: line 130:  7762 Segmentation fault      (core dumped) $bindir/smis_sort bwa_sorted.bam
wc: '/media/mml/7f555590-c3e2-4192-a443-b767d932b613/RNAseq/RNAseq/KG/ct-pacbio_data/CATR/smisrunbhagya/tempWork/genome-matepair-*': No such file or directory
cannot open file genome.fasta
mv: cannot stat 'spinner-sp2b.fasta': No such file or directory

 Scaffolds are in spinner_scaffolds.fasta
 Summary of parameters used are in  /media/mml/7f555590-c3e2-4192-a443-b767d932b613/RNAseq/RNAseq/KG/ct-pacbio_data/CATR/smisrunbhagya/logs/launchedas_1506156060.txt
 Log is in  /media/mml/7f555590-c3e2-4192-a443-b767d932b613/RNAseq/RNAseq/KG/ct-pacbio_data/CATR/smisrunbhagya/logs/output_1506156060.txt
 
Thank you
Bhagya C T

**Comment by fg6** [comment]
Hi Bhagya,
thanks for the info. 
A first check to do is to please make sure the fastq file and the fasta file with their full paths
are given to the script. You can check this by looking into your project folder (destdir) and open with a text editor the mysettings.sh file and look for the variable fafile and fqfile. 
If you don't have the full path to your files then please pull the new smis version in your smis folder (I have added some additional checks) and please restart your project folder by relaunching the setup command (from your smis folder):
./setup.sh </full/path/to/destdir> </full/path/to/draft_assembly> </full/path/to/long_reads>

If you still have seg fault, then please send me some additional information:
1. which gcc are you using?
2. which parameters are you using for minlen, fakelen and step? (if you didn't modify your settings file just say default values)
3. what are the characteristics of your fastq file? Like mean read length, number of reads, total number of bases,...
4. what are the characteristics of your fasta file? Like mean read length, number of reads, total number of bases,...

Thank you,
Francesca

**Comment by bhagya-ct** [comment]
Dear Developer

Thank you for the help, it is working (closed 4 gaps out of 24). Genome is more repetitive and PacBio reads that we got were not great so I am not surprised with the result.

Once again, thank you for your support.

Bhagya C T

**Comment by fg6** [comment]
Glad it works !
